-- Deduplicated DDL for rps.document_item / EDW.DOCUMENT_ITEM_RPS.
CREATE TABLE EDW.DOCUMENT_ITEM_RPS (
  `SERVER_NAM` String,
  `SID` Decimal(19, 0),
  `CREATED_BY` String,
  `MODIFIED_BY` String,
  `CONTROLLER_SID` Decimal(19, 0),
  `ORIGIN_APPLICATION` String,
  `ROW_VERSION` Decimal(10, 0),
  `TENANT_SID` Decimal(19, 0),
  `DOC_SID` Decimal(19, 0),
  `ITEM_POS` Decimal(5, 0),
  `INVN_SBS_ITEM_SID` Decimal(19, 0),
  `DETAX_FLAG` Decimal(1, 0),
  `KIT_FLAG` Decimal(2, 0),
  `PROMOTION_FLAG` Decimal(1, 0),
  `GIFT_ADD_VALUE` Decimal(1, 0),
  `ARCHIVED` Decimal(1, 0),
  `ST_PRIMARY` Decimal(1, 0),
  `STORE_NO` Decimal(5, 0),
  `COMM_CODE` Decimal(5, 0),
  `ST_PRICE_LVL` Decimal(5, 0),
  `QTY` Decimal(10, 3),
  `ORIG_PRICE` Decimal(16, 4),
  `ORIG_TAX_AMT` Decimal(16, 4),
  `PRICE` Decimal(16, 4),
  `TAX_PERC` Decimal(16, 4),
  `TAX_AMT` Decimal(17, 5),
  `TAX2_PERC` Decimal(16, 4),
  `TAX2_AMT` Decimal(17, 5),
  `PRICE_BEFORE_DETAX` Decimal(16, 4),
  `ORIG_PRICE_BEFORE_DETAX` Decimal(16, 4),
  `COST` Decimal(16, 4),
  `SPIF` Decimal(16, 4),
  `SCHEDULE_NO` Decimal(5, 0),
  `SCAN_UPC` Decimal(18, 0),
  `SERIAL_NO` String,
  `PACKAGE_INVN_SBS_ITEM_SID` Decimal(19, 0),
  `ORIG_CMPNT_INVN_SBS_ITEM_SID` Decimal(19, 0),
  `USER_DISC_PERC` Decimal(16, 4),
  `PACKAGE_SEQUENCE_NO` Decimal(5, 0),
  `LOT_NO` String,
  `ACTIVITY_PERC` Decimal(16, 4),
  `ACTIVITY2_PERC` Decimal(16, 4),
  `ACTIVITY3_PERC` Decimal(16, 4),
  `ACTIVITY4_PERC` Decimal(16, 4),
  `ACTIVITY5_PERC` Decimal(16, 4),
  `COMM_AMT` Decimal(16, 4),
  `COMM2_AMT` Decimal(16, 4),
  `COMM3_AMT` Decimal(16, 4),
  `COMM4_AMT` Decimal(16, 4),
  `COMM5_AMT` Decimal(16, 4),
  `ITEM_ORIGIN` Decimal(1, 0),
  `PACKAGE_NO` String,
  `SHIP_ID` Decimal(10, 0),
  `ORIG_COST` Decimal(16, 4),
  `GIFT_ACTIVATION_CODE` String,
  `GIFT_TRANSACTION_ID` String,
  `CUST_FIELD` String,
  `UDF1_STRING` String,
  `UDF2_STRING` String,
  `UDF3_STRING` String,
  `UDF4_STRING` String,
  `UDF5_STRING` String,
  `UDF1_FLOAT` Decimal(16, 4),
  `UDF2_FLOAT` Decimal(16, 4),
  `UDF3_FLOAT` Decimal(16, 4),
  `DISC_PERC` Decimal(16, 4),
  `NOTE1` String,
  `NOTE2` String,
  `NOTE3` String,
  `NOTE4` String,
  `NOTE5` String,
  `NOTE6` String,
  `NOTE7` String,
  `NOTE8` String,
  `NOTE9` String,
  `NOTE10` String,
  `DISC_AMT` Decimal(16, 4),
  `ITEM_TYPE` Decimal(1, 0),
  `DCS_CODE` String,
  `VEND_CODE` String,
  `DESCRIPTION1` String,
  `DESCRIPTION2` String,
  `DESCRIPTION3` String,
  `DESCRIPTION4` String,
  `ATTRIBUTE` String,
  `ITEM_SIZE` String,
  `ALU` String,
  `TAX_CODE` String,
  `TAX_CODE2` String,
  `COMM_LVL` String,
  `COMM_PERC` Decimal(16, 4),
  `ST_ADDRESS_LINE1` String,
  `ST_ADDRESS_LINE2` String,
  `ST_ADDRESS_LINE3` String,
  `ST_ADDRESS_LINE4` String,
  `ST_ADDRESS_LINE5` String,
  `ST_ADDRESS_LINE6` String,
  `ST_COUNTRY` String,
  `ST_POSTAL_CODE` String,
  `ST_POSTAL_CODE_EXTENSION` String,
  `EMPLOYEE1_LOGIN_NAME` String,
  `EMPLOYEE1_FULL_NAME` String,
  `EMPLOYEE2_LOGIN_NAME` String,
  `EMPLOYEE2_FULL_NAME` String,
  `EMPLOYEE3_LOGIN_NAME` String,
  `EMPLOYEE3_FULL_NAME` String,
  `EMPLOYEE4_LOGIN_NAME` String,
  `EMPLOYEE4_FULL_NAME` String,
  `EMPLOYEE5_LOGIN_NAME` String,
  `EMPLOYEE5_FULL_NAME` String,
  `ST_CUID` Decimal(19, 0),
  `ST_ID` Decimal(19, 0),
  `ST_COMPANY_NAME` String,
  `ST_LAST_NAME` String,
  `ST_FIRST_NAME` String,
  `ST_TITLE` String,
  `ST_TAX_AREA_NAME` String,
  `ST_TAX_AREA2_NAME` String,
  `ST_PRICE_LVL_NAME` String,
  `ST_DETAX_FLAG` Decimal(1, 0),
  `ST_PRIMARY_PHONE_NO` String,
  `DISCOUNT_REASON` String,
  `ORDER_TYPE` Decimal(5, 0),
  `ST_EMAIL` String,
  `SO_NUMBER` Decimal(14, 0),
  `SHIP_METHOD` String,
  `SHIP_AMT` Decimal(16, 4),
  `HIST_DISC_AMT1` Decimal(16, 4),
  `HIST_DISC_PERC1` Decimal(16, 4),
  `HIST_DISC_REASON1` String,
  `HIST_DISC_AMT2` Decimal(16, 4),
  `HIST_DISC_PERC2` Decimal(16, 4),
  `HIST_DISC_REASON2` String,
  `HIST_DISC_AMT3` Decimal(16, 4),
  `HIST_DISC_PERC3` Decimal(16, 4),
  `HIST_DISC_REASON3` String,
  `HIST_DISC_AMT4` Decimal(16, 4),
  `HIST_DISC_PERC4` Decimal(16, 4),
  `HIST_DISC_REASON4` String,
  `HIST_DISC_AMT5` Decimal(16, 4),
  `HIST_DISC_PERC5` Decimal(16, 4),
  `HIST_DISC_REASON5` String,
  `PRICE_LVL` Decimal(5, 0),
  `PRICE_LVL_NAME` String,
  `ST_SECURITY_LVL` Decimal(5, 0),
  `TRACKING_NO` String,
  `INVENTORY_ITEM_TYPE` Decimal(1, 0),
  `INVENTORY_OH_QTY` Decimal(10, 3),
  `INVENTORY_QTY_PER_CASE` Decimal(10, 3),
  `GIFT_EXPIRE_DATE` Date32,
  `OVERRIDE_MAX_DISC_PERC` Decimal(16, 4),
  `SBS_NO` Decimal(5, 0),
  `RETURNED_ITEM_QTY` Decimal(10, 3),
  `RETURNED_ITEM_INVOICE_SID` Decimal(19, 0),
  `RETURN_REASON` String,
  `PRICE_LVL_SID` Decimal(19, 0),
  `ORDER_QUANTITY_FILLED` Decimal(10, 3),
  `GIFT_QUANTITY` Decimal(10, 3),
  `SO_DEPOSIT_AMT` Decimal(16, 4),
  `REF_ORDER_ITEM_SID` Decimal(19, 0),
  `TAX_AREA_NAME` String,
  `TAX_AREA2_NAME` String,
  `SERIAL_TYPE` Decimal(1, 0),
  `LOT_TYPE` Decimal(1, 0),
  `SEND_SALE_FLAG` Decimal(1, 0),
  `FULFILL_STORE_NO` Decimal(5, 0),
  `FULFILL_STORE_SID` Decimal(19, 0),
  `FULFILL_SBS_NO` Decimal(5, 0),
  `SO_CANCEL_FLAG` Decimal(1, 0),
  `CENTRAL_DOCUMENT_SID` Decimal(19, 0),
  `CENTRAL_ITEM_POS` Decimal(5, 0),
  `EMPLOYEE1_SID` Decimal(19, 0),
  `EMPLOYEE2_SID` Decimal(19, 0),
  `EMPLOYEE3_SID` Decimal(19, 0),
  `EMPLOYEE4_SID` Decimal(19, 0),
  `EMPLOYEE5_SID` Decimal(19, 0),
  `DIP_PRICE` Decimal(16, 4),
  `DIP_DISC_AMT` Decimal(16, 4),
  `DIP_TAX_AMT` Decimal(17, 5),
  `DIP_TAX2_AMT` Decimal(17, 5),
  `ITEM_STATUS` Decimal(1, 0),
  `ENHANCED_ITEM_POS` Decimal(10, 0),
  `IS_COMPETING_COMPONENT` Decimal(1, 0),
  `PROMO_MANDISC` Decimal(1, 0),
  `SHIP_METHOD_SID` Decimal(19, 0),
  `SHIP_METHOD_ID` Decimal(5, 0),
  `ORDER_SHIP_METHOD_SID` Decimal(19, 0),
  `ORDER_SHIP_METHOD_ID` Decimal(5, 0),
  `ORDER_SHIP_METHOD` String,
  `TAX_PERC_LOCK` Decimal(1, 0),
  `QTY_AVAILABLE_FOR_RETURN` Decimal(10, 3),
  `CENTRAL_RETURN_COMMIT_STATE` Decimal(1, 0),
  `INVN_USE_QTY_DECIMALS` Decimal(1, 0),
  `SHIP_AMT_BDT` Decimal(16, 4),
  `TAX_CODE_RULE_SID` Decimal(19, 0),
  `TAX_CODE_RULE2_SID` Decimal(19, 0),
  `ST_ADDRESS_UID` Decimal(19, 0),
  `ORIG_SALE_PRICE` Decimal(16, 4),
  `LTY_PGM_SID` Decimal(19, 0),
  `LTY_PGM_NAME` String,
  `LTY_POINTS_EARNED` Decimal(24, 8),
  `LTY_ORIG_POINTS_EARNED` Decimal(24, 8),
  `LTY_PRICE_IN_POINTS` Decimal(24, 8),
  `LTY_ORIG_PRICE_IN_POINTS` Decimal(24, 8),
  `LTY_TYPE` Decimal(1, 0),
  `LTY_PIECE_OF_TBE_POINTS` Decimal(16, 4),
  `LTY_PIECE_OF_TBR_POINTS` Decimal(16, 4),
  `LTY_PIECE_OF_TBR_DISC_AMT` Decimal(16, 4),
  `EFTDATA1` String,
  `EFTDATA2` String,
  `EFTDATA3` String,
  `EFTDATA4` String,
  `EFTDATA5` String,
  `EFTDATA6` String,
  `EFTDATA7` String,
  `EFTDATA8` String,
  `EFTDATA9` String,
  `EFTDATA0` String,
  `EFTDATA10` String,
  `EFTDATA11` String,
  `EFTDATA12` String,
  `EFTDATA13` String,
  `EFTDATA14` String,
  `EFTDATA15` String,
  `EFTDATA16` String,
  `EFTDATA17` String,
  `EFTDATA18` String,
  `EFTDATA19` String,
  `EFTDATABSMER` String,
  `EFTDATABSCUST` String,
  `ACTIVATION_SID` Decimal(19, 0),
  `PROMO_GIFTITEM` Decimal(1, 0),
  `INTERNAL_ITEM_POS` Decimal(5, 0),
  `DIP_PRICE_BDT` Decimal(16, 4),
  `UPDATE_DL_TS` DateTime64(3, 'UTC'),
  `CREATED_DATETIME` String,
  `MODIFIED_DATETIME` String,
  `POST_DATE` String,
  `UDF1_DATE` String,
  `AUTHORIZE_DATE` String,
  `DL_TS` String,
  `month` LowCardinality(String),
  `year` Int64,
  `_path` LowCardinality(String),
  `_file` LowCardinality(String),
  `_size` Nullable(UInt64),
  `_time` Nullable(DateTime)
)
ENGINE = SharedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', UPDATE_DL_TS)
PARTITION BY SERVER_NAM
PRIMARY KEY SID
ORDER BY SID
SETTINGS index_granularity = 8192;
